spring:
  application:
    name: discodeit

  profiles:
    active: test

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  boot:
    admin:
      client:
        instance:
          name: Discodeit

discodeit:
  storage:
    type: local
    local:
      root-path: temp

logging:
  level:
    root: info
