spring:
  application:
    name: discodeit
  servlet:
    multipart:
      enabled: true

discodeit:
  repository:
    type: jcf # jcf | file
    file-directory: temp

server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# swagger
springdoc:
  api-docs:
    path: /api-docs     # OpenAPI 명세서의 엔드포인트 설정 (기본값: /v3/api-docs)
  default-consumes-media-type: application/json   # 기본 요청 Content-Type
  default-produces-media-type: application/json   # 기본 응답 Content-Type
  swagger-ui:
    operations-sorter: alpha    # API 메서드 알파벳 순 정렬
    tags-sorter: alpha          # API 태그 알파벳 순 정렬
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true