# PROD

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # 배포용 DB
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_DATABASE}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
        generate_statistics: false
        cache:
          use_second_level_cache: false
      open-in-view: false

# logging
logging:
  level:
    root: info
    com.sprint.mission.discodeit: info
    org:
      hibernate:
        sql: debug

# swagger
springdoc:
  api-docs:
    path: /api-docs     # OpenAPI 명세서의 엔드포인트 설정 (기본값: /v3/api-docs)
  default-consumes-media-type: application/json   # 기본 요청 Content-Type
  default-produces-media-type: application/json   # 기본 응답 Content-Type
  swagger-ui:
    operations-sorter: alpha    # API 메서드 알파벳 순 정렬
    tags-sorter: alpha          # API 태그 알파벳 순 정렬
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true

# port
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: utf-8