spring:
  application:
    name: discodeit
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  boot:
    admin:
      client:
        #        url: http://localhost:9090
        #        instance:
        #          service-url: http://localhost:8080
        #          management-url: http://localhost:8080/actuator
        #          health-url: http://localhost:8080/actuator/health
        #          name: spring-boot-application
        enabled: false

discodeit:
  storage:
    type: local
    local:
      root-path: temp

logging:
  level:
    root: info
