spring:
  application:
    name: discodeit
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true

discodeit:
  storage:
    type: local
    local:
      root-path: temp

logging:
  level:
    root: info