spring:
  application:
    name: discodeit

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
  boot:
    admin:
      client:
        instance:
          name: Discodeit

  cache:
    cache-names: userChannels, userNotifications, allUsers

  kafka:
    bootstrap-servers: ${KAFKA_NAME}:${KAFKA_INNER_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: discodeit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: batch

discodeit:
  storage:
    type:
      ${STORAGE_TYPE:local}
    local:
      root-path: ${STORAGE_LOCAL_ROOT_PATH:temp}
    s3:
      access-key-id: ${AWS_ACCESS_KEY_ID}
      secret-access-key: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      presigned-url-expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL}
  cookie:
    persistent-key: ${PERSISTENT_COOKIE_KEY}
  jwt:
    secret: ${JWT_SECRET_KEY}
    access-token-expiration: 900000     # 15min
    refresh-token-expiration: 604800000   # 7day

logging:
  level:
    root: info