spring:
  application:
    name: discodeit
  servlet:
    multipart:
      enabled: true
  # DB - postgreSQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        generate_statistics: true
        cache:
          use_second_level_cache: false
      open-in-view: false

  transaction:
    default-timeout: 30

discodeit:
  storage:
    type: local
    local:
      root-path: temp

server:
  tomcat:
    uri-encoding: utf-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# logging
logging:
  level:
    org:
      hibernate:
        sql: debug
        type.descriptor.sql.BasicBinder: trace

# swagger
springdoc:
  api-docs:
    path: /api-docs     # OpenAPI 명세서의 엔드포인트 설정 (기본값: /v3/api-docs)
  default-consumes-media-type: application/json   # 기본 요청 Content-Type
  default-produces-media-type: application/json   # 기본 응답 Content-Type
  swagger-ui:
    operations-sorter: alpha    # API 메서드 알파벳 순 정렬
    tags-sorter: alpha          # API 태그 알파벳 순 정렬
    path: /swagger-ui
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true